[
  {
    id: 1,
    body: 'The Collectorate Eidgah ground in Rangpur, which is the venue for today\'s BNP divisional rally, was flooded with BNP supporters and activists this morning (October 29, 2022).\r\n\r\nLeaders and activists are arriving in groups holding processions and chanting slogans, reports our local correspondent.\r\nMany arrived last night from Bogura, Joypurhat, and other districts besides the ones in the Rangpur division. Many of them camped and spent the night at the rally venue.\r\n\r\nHundreds of people on battery-run three-wheelers were seen on the adjacent highways leading to the district.  \r\nMahbubur Rahman, a leader of Kurigram\'s Nageswari Upazila BNP unit, said they had left on 50 three-wheelers around 9:00 pm last night and arrived at the district this morning.\r\n\r\n"We then walked to the venue from the Satmatha area in the district," he said adding that due to the strike, they had to make the three-hour bus journey in nine hours.\r\n\r\nIn the morning, visiting various areas of Rangpur, it was seen that people coming by three-wheelers from Kurigram are Lalmonirhat are getting off in Satmatha intersection and walking on foot towards the rally venue.\r\nOn the other hand, people from Pirganj and Gaibandha were seen arriving in three-wheelers in the Rangpur Bus Terminal area.\r\n\r\nMeanwhile, police presence was beefed up in Rangpur city since morning. There are backup forces ready in the police line area to tackle any untoward situation, police officials said.\r\n\r\nAt a press conference yesterday (October 28, 2022), BNP vice chairman AZM Zahid Hossain said the transport strike "called by the government" to foil BNP\'s rally will cause suffering to the people, but they will travel either on foot or in auto-rickshaws from eight districts of Rangpur division to join the rally. Although the rally was scheduled to begin in the afternoon, he said that it would begin at 11am.',
    category_name: "Politics",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "top news",
    date: "28 October, 2022 15:21",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667024293918.jpg",
    headline: "3 hours journeys made in 9: Rangpur rally venue packed",
    editor_name: "Md Iqbal Hossen",
  },
  {
    id: 2,
    body: "A World Bank survey conducted between June 2020 and May 2022 has found that around 30 percent of people in Bangladesh are currently facing food scarcity. This is despite the fact that the country's economy made a recovery from pandemic-induced shocks, according to the report. The survey has found that 13 percent of people went to sleep hungry in May this year, compared to seven percent in June 2021. During the same time, the number of people who could not afford to buy food and those who didn't eat in 24 hours also increased. These findings have been revealed at a time when we are already worried about the rising inflation that has affected purchasing capacities and the food shortage that the country might face in the coming months. \r\nIt is true that our economy showed some quick signs of recovery after the first two waves of the Covid-19 pandemic, but before its effects could trickle down to the poverty-stricken people, they were left to confront the cost of living crisis. Against the backdrop of the Russia-Ukraine war, and thanks to poorly thought-out interventions by the government, inflation has now surged out of control, further reducing people's access to food. Although the government has taken some measures to provide essential food items to the poor at subsidized prices, they have been woefully inadequate in reaching all the people who need such assistance. The government's inability to check inflation means that more and more people are having to make compromises on their nutritional needs. \r\nCurrently, 68 percent of the county's population is struggling to buy food due to their sky-rocketing prices, according to a survey by the World Food Programme. These people, who do not have enough cash to meet the day-to-day food expenses of their families, are either being forced to take loans or use up their savings. At present, it is not only rice, wheat, meat, and vegetables that are being sold at extremely high prices, but even eggs, a low-cost source of protein for low-income people, have gone out of reach for many. \r\nSo, how to bring the situation under control? The government should not only take concrete measures to check food inflation – by importing food grains and bringing down food prices through proper market interventions – but it should also strengthen its Vulnerable Group Feeding (VGF) and Food For Work (FFW) programs to reduce food insecurity. While these steps can give some temporary relief to those most vulnerable, as long-term measures, we should focus on increasing our own food production in order to avert any future food crisis. Since the country is continuing to regularly face natural disasters, including floods and the recent cyclone, the farmers in the affected areas need to be given cash incentives as well as fertilizers and fuel for irrigation at subsidized prices. The food scarcity and high inflation in the country can only be checked through proper policies and their effective implementation.",
    category_name: "World",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "genaral news",
    date: "29 October, 2022 12:22",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667024558015.png",
    headline: "On the verge of starvation",
    editor_name: "Iqbal",
  },
  {
    id: 3,
    headline: "Gujarat bridge collapse: Death toll rises to 130",
    body: 'The death toll from the collapse of a suspension bridge over a river in the western Indian state of Gujarat\'s Morbi town mounted to 130 this morning (October 31, 2022) as rescue officials fished out more bodies.\r\n\r\n"132 deaths have been reported so far," Gujarat Home Minister Harsh Sanghavi told the media, reports our New Delhi correspondent.\r\n\r\nA criminal case has been registered. An investigation has begun today under the leadership of Range IGP, he said.\r\n\r\n"More than 100 deaths have been reported till early morning. Around 177 people have been rescued. Nineteen people are under treatment," Gujarat Information Department said adding the army, navy, air force, National Disaster Response Force (NDRF) and fire brigade personnel are conducting search operations.\r\n\r\nThe more than a century-old bridge in Morbi city crashed at around 6.30 pm on Sunday when it was crammed with people.\r\n\r\n"The search and rescue operation is still underway. The Indian army reached the incident site at around 3 am at night. We are trying to recover the bodies. Teams of NDRF are also carrying out rescue operations," Major Gaurav of the Indian Army said.\r\n\r\nThe National Disaster Response Force on Sunday rushed three teams to Morbi. NDRF Director General (DG) Atul Karwal said each of the three teams comprises 30 rescuers and four boats and is led by senior officers.\r\nHarsh Sanghavi said an FIR has been registered against the private firm, which renovated the suspension bridge over the Machchu river, on the charge of attempt to commit culpable homicide and culpable homicide not amounting to murder under Indian Penal Code section 304.\r\n\r\nAn official said that the suspension bridge reopened for the public just four days before the accident after seven months of repair work by the private firm had not received the local municipality\'s "fitness certificate".\r\n\r\n"The bridge was given to Oreva company for operation and maintenance for 15 years. In March this year, it was closed to the public for renovation. It reopened after renovation on the Gujarati New Year day celebrated on October 26," said Chief Officer of Morbi Municipality Sandeepsinh Zala.\r\n\r\n"It was reopened to the public after the completion of the renovation work. But the local municipality had not yet issued any fitness certificate (after the renovation work)," he said.\r\n\r\nSeveral leaders of the opposition Congress party attacked Gujarat\'s ruling BJP over the bridge collapse. The party\'s spokesman Randeep Surjewala termed it a "man-made tragedy" and accused the state government of being directly responsible for it.\r\n\r\nSenior Congress leader Digvijaya Singh asked if the incident was an "act of God or an act of fraud".',
    category_name: "Politics",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "hot news",
    editor_name: "Iqbal Hossen",
    date: "29 October, 2022 12:22",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667186337845.png",
  },
  {
    id: 4,
    headline: "All cities need a DAP of their own",
    body: "Not long ago, we commented on the government's plan to establish five new development authorities in Sylhet, Payra, Rangpur, Barishal, and Mymensingh. Already, there are a number of similar development authorities – in Dhaka, Cox's Bazar, Khulna, Rajshahi, Gazipur, and Chattogram. What's common to these region-specific development agencies is their lack of effect, as they are hamstrung by manpower shortage, wasteful or unaccountable spending, lack of initiative to uphold their mandate, non-cooperation from other government departments, etc. Clearly, setting up new agencies without fixing these institutional challenges runs the risk of making them similarly ineffective. Is more of Rajuk what Bangladesh needs at this moment?\r\nExperts at a recent roundtable covered by Prothom Alo have raised an equally important question: Is more Dhaka-focused development good for the future of Dhaka and, by extension, Bangladesh? Clearly, it is not. Dhaka has become a colossal primate city, larger than the next three big cities combined. Yet, we continue to keep our urban policies centered on Dhaka which has done little to make it liveable. This Dhaka-centrism has hurt Dhaka more than it benefitted it, or its residents, while a lack of focus on other cities and metropolises has resulted in them lagging behind in terms of growth opportunities. This is why experts have called for a policy of equitable urban development across the country, one that will take some of the pressure off the capital, and offer all other regions equal access to economic and administrative opportunities, civic amenities, quality healthcare, and education, etc. With the fallout of climate change being felt across the coast, this is all the more important. We need to prepare our cities to accommodate the growing number of climate refugees so that their burden doesn't fall disproportionately on Dhaka. Bangladesh is going through a rapid change, a deeply unsustainable urbanization process that makes any future planning difficult. But we must try. The recently unveiled Detailed Area Plan (DAP) for Dhaka has been criticized by environmental and urban experts for not reflecting the need for the best use of available spaces and resources, and it doesn't help that a clueless and, frankly, rudderless Rajuk is in charge of moving the needle on this front.\r\nAs one expert has said at the roundtable, we need a DAP for each (mid-sized) city and properly staffed and motivated agencies in charge of their development. Only then will the country's development become equitable and sustainable, its benefits reaching every citizen. As well as addressing housing and other liveability issues, such policies must preserve what remains of our agricultural lands for the sake of our present and future food safety. They must allow for more playgrounds, open spaces, and schools within walking distances, and for villages to coexist with equal importance. And all initiatives must be part of a national urban policy, which is yet to be formulated, for better coordination and more balanced development. Otherwise, the government's Vision 2041 will remain only in words.",
    category_name: "Business",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "hot news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 10:8",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667189280704.png",
  },
  {
    id: 5,
    headline:
      "Indian govt urges SC to dismiss pleas challenging the validity of CAA",
    body: 'The Indian government has urged the Supreme Court to dismiss pleas challenging the validity of the Citizenship (Amendment) Act (CAA), saying it is a "focused law" that grants citizenship only to members of six specified communities who came to India on or before December 31, 2014.\r\n\r\nA bench, comprising Chief Justice Uday Umesh Lalit and justices S Ravindra Bhat and Bela M Trivedi, is scheduled to hear 232 petitions, mostly PILs, tomorrow (on October 31) on the issue of CAA, reports our New Delhi correspondent.\r\n\r\nIn a detailed 150-page affidavit, the Indian Home Ministry said "parliament is competent to make laws for the whole or any part of the territory of India as provided in Article 245 (1) of The Constitution of India."\r\n\r\nSeeking dismissal of the pleas, the affidavit, filed by Sumant Singh, a joint secretary in the Home Ministry, said the CAA, 2019 "facilitates the grant of citizenship to migrants belonging to Hindu, Sikh, Buddhist, Jain, Parsi and Christian communities from Afghanistan, Bangladesh and Pakistan who entered in India on or before December 31, 2014."\r\nIt said the law applied to those who have been exempted by the central government under the provisions of the Passport (Entry into India) Act, 1920 and other relevant provisions and the rules made under the Foreigners Act, 1946.\r\n\r\n',
    category_name: "World",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "top news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 10:23",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667190209218.jpg",
  },
  {
    id: 6,
    headline:
      "Pakistani journalist crushed to death by ex-PM Imran's convoy during the coverage",
    body: "Sadaf Naeem, a reporter covering the PTI's long march for Channel 5, was crushed to death during an accident near Sadhoke on Sunday.\r\n\r\nAccording to Channel 5, the reporter was run over by PTI Chairman Imran Khan's container. The media outlet said that Naeem fell from the container after which she was crushed by the vehicle.\r\nA Dawn.com correspondent on the container, however, said that Naeem slipped while trying to climb the container.\r\n\r\nPTI leader Fawad Chaudhry confirmed the development, saying that a female media personnel was killed and that Imran had himself gotten off the vehicle to inspect the incident while Rescue 1122 was alerted as well.\r\n\"We are not 100 per cent sure about the identity but the reports are very bad,\" he said prior to the confirmation by the channel.\r\n\r\nFawad requested the public to take caution while walking along Imran's container, adding that the lives of all people contributing to the march were \"precious and respected\".\r\n\r\nAs a result of the incident, the PTI called off today's activities in solidarity.",
    category_name: "World",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "top news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 10:24",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667190278264.jpg",
  },
  {
    id: 7,
    headline: "Allow the civil society to have a voice: UN special rapporteur",
    body: 'The UN Special Rapporteur on Human Rights and Climate Change has suggested that the Bangladesh government allow freedom of expression, particularly on the issue of promoting and protecting human rights related to climate change.\r\n\r\n"In the lead-up to the next election, I encourage the government of Bangladesh to allow civil society to have a voice. Suppression of such voice will only lead to malcontent," said the UN Special Rapporteur Ian Fry in a report.\r\nThe report prepared based on his visit to Bangladesh on September 4-15 was presented by Saleemul Huq, director of the International Centre for Climate Change and Development (ICCCAD) at a discussion at a city hotel yesterday.\r\n\r\nExperts, UN officials, and policymakers were present at the event moderated by UN Resident Coordinator Gwyn Lewis.',
    category_name: "Bangladesh",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "features ",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 10:34",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667190885427.jpg",
  },
  {
    id: 8,
    headline: "How erratic weather has affected our food production",
    body: "The Sixth Assessment Report (AR6) by the Working Group II of the Intergovernmental Panel on Climate Change (IPCC) shows how food production is at risk because of heat and drought. The report anticipates more severe food security risks due to climate change, leading to malnutrition in South Asia, one of the global hotspots of high human vulnerability, due to global warming of two degrees Celsius or higher. Unfortunately, it is already evident in countries like Bangladesh, especially in climate-vulnerable areas.\r\n\r\nIn July 2022, Bangladesh experienced the lowest rainfall in 41 years. It has significantly affected climate change adaptation practices in vulnerable communities, causing more loss and damage. In the short run, these impacts fuelled food price hikes and reduced household income. The health risk of malnutrition because of the low level of adaptation, in the short to middle run, has been estimated as well.",
    category_name: "Bangladesh",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "features",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 10:35",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667190950066.jpg",
  },
  {
    id: 9,
    headline: "Pacers leading the pack for Tigers",
    body: "The fast-bowling department has stood out in Bangladesh's two wins in the ongoing ICC T20 World Cup, and it was pacer Taskin Ahmed who rose to the occasion yet again as Tigers clinched a hard-fought three-run win over Zimbabwe in their third Super 12 game at the Gabba yesterday.\r\n\r\nIt will be hard to recall when was the last time a fast bowler picked up two player-of-the-match awards for Bangladesh, and that too in a World Cup, as Taskin showed his consistency and vast improvement of late to emerge as a world-class act for the Tigers.\r\nThe 27-year-old ended up with the figures of three for 19 from his four overs, at an economy of 4.75, to stage a successful defense of a modest 151-run target. Taskin spearheaded the three-men Bangladesh pace-bowling unit with experienced Mustafizur Rahman and young Hasan Mahmud to aid the Tigers in snatching a dramatic win.\r\n\r\nTaskin's transformation as a fast bowler is now paying dividends and, most importantly, he has given Bangladesh the much-needed strength in pace-friendly Australian conditions.",
    category_name: "Bangladesh",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "features",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 10:37",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667191042903.jpg",
  },
  {
    id: 10,
    headline: "Tigers win ‘twice’ in a match",
    body: "The match ended once, only it did not. Plenty of back-patting among the Bangladesh players only to be left quite perplexed just as the crowd was with the players asked to come back in.\r\n\r\nThe mowers and the rollers had made their way into the ground with the Bangladesh team management members congratulating one another near the touchline on a memorable victory. The players were all off the field but the nerves that had just been relieved all rushed back in as umpire Marais Erasmus signaled no-ball, meaning Mosaddek Hossain had to bowl that final delivery again.\r\nWhat transpired before that point had already left everyone on the edge of their seats. By no means a death overs specialist, all-rounder Mosaddek had been asked to do the job of defending 16 runs in the last over by skipper Shakib Al Hasan. He fired one at Ryan Burl's pads as Zimbabwe ran for a leg-bye and that was critical as Burl, the recognized batter batting on 27, did not get the strike again.\r\n\r\nBrad Evans then failed to muscle it out of the ground and departed as Mosaddek started brilliantly but Richard Ngarava produced four leg-byes before he swung one way over the deep fine-leg fence for six. Five needed off two deliveries and match on a knife's edge, Mosaddek showed nerves of steel and flighted one up that beat the batter and Nurul Hasan Sohan was quick to get the bails off. Five needed off one and Blessing Muzarabani gave it his all but got no bat on it as Sohan once again took off the stumps. Bangladesh celebrated as players left the field after shaking hands but it turned out that the wicketkeeper had collected the ball just in front of the line of the stumps. No ball was called and the last delivery was a free hit.",
    category_name: "Bangladesh",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "features",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 10:40",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667191233308.jpg",
  },
  {
    id: 11,
    headline:
      "How to avoid conflict of interest in resolving election stalemate",
    body: "Two major political parties in Bangladesh are on a collision course. The opposition demands the next general election to help under an impartial, caretaker government. The ruling party is staunchly against that. It is not hard to guess that next year will likely be a time of political unrest, social instability and turmoil. This is undesirable when the country just came out of a pandemic and the world is heading towards an economic downturn.\r\n\r\nI had the opportunity to be a part of the Bangladesh Civil Service (Administration) for some time and was involved with election duties in many capacities. Voting can be manipulated through many tactics. The common scenarios include polling centres being overrun by political musclemen, vote-counting being influenced at the presiding or returning officer's level, law enforcement officials taking over the control of polling centres allowing ballot-stuffing, etc. All these can happen either by direct patronisation of the administration or because of their blindness.\r\n\r\nUnder an incumbent government, the Election Commission may not be able to exercise its full control over the field administration for various reasons, but the most important is the \"conflict of interest.\" This occurs when an individual's personal interests compromise his or her judgement, decisions or actions. A conflict of interest, since it blurs normal judgement, must be taken very seriously while assigning important responsibilities. Deputy commissioners (DCs) and superintendents of police (SPs) – two main facilitators of an election – become so perniciously politicised during normal times and benefit from the ruling regime that they find it essential for their own sakes to keep the status quo. Under such a situation, assigning them election-related responsibilities creates a strong conflict of interest.\r\n\r\nAn election process broadly consists of (1) administering the voting and vote-counting process; and (2) maintenance of law and order. Election commissioners are tenured for five years with high status and handsome remuneration. This can provide a strong temptation for anyone to remain in that position for as long as possible, by any means. A long period also exposes the election commissioners to the risk of being politicised.",
    category_name: "Bangladesh",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "features ",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 10:41",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667191319328.jpg",
  },
  {
    id: 12,
    headline: "Gujarat bridge collapse: Death toll rises to 130",
    body: 'The death toll from the collapse of a suspension bridge over a river in the western Indian state of Gujarat\'s Morbi town mounted to 132 this morning (October 31, 2022) as rescue officials fished out more bodies.\r\n\r\n"132 deaths have been reported so far," Gujarat Home Minister Harsh Sanghavi told the media, reports our New Delhi correspondent.\r\nA criminal case has been registered. An investigation has begun today under the leadership of Range IGP, he said.\r\n\r\n"More than 100 deaths have been reported till early morning. Around 177 people have been rescued. Nineteen people are under treatment," Gujarat Information Department said adding the army, navy, air force, National Disaster Response Force (NDRF) and fire brigade personnel are conducting search operations.\r\nThe more than a century-old bridge in Morbi city crashed at around 6.30 pm on Sunday when it was crammed with people.\r\n\r\n"The search and rescue operation is still underway. The Indian army reached the incident site at around 3 am at night. We are trying to recover the bodies. Teams of NDRF are also carrying out rescue operations," Major Gaurav of the Indian Army said.\r\n\r\nThe National Disaster Response Force on Sunday rushed three teams to Morbi. NDRF Director General (DG) Atul Karwal said each of the three teams comprises 30 rescuers and four boats and is led by senior officers.',
    category_name: "Politics",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "genaral news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 10:49",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667191746047.png",
  },
  {
    id: 13,
    headline: "Rein in tax exemptions",
    body: 'Known knowns -- is what best sums up the prognosis of the visiting International Monetary Fund mission so far as it looks to thrash out the conditions for the prospective $4.5 billion loan.\r\n\r\nTake, for instance, the prescription to the National Board of Revenue yesterday during the staff mission\'s second full day of meetings after it arrived in Dhaka on a 15-day tour.\r\nThe mission called for bringing down tax exemptions, which include complete relief from taxes, reduced rates, or tax on only a portion of items.\r\n\r\nIt is a well-established fact by now that the tax exemptions in Bangladesh are unsustainably high and need to be reined in.\r\nAnd yet, not much has been done on that front over the years.\r\n\r\nWhat is worse is the government has no idea how much the state coffer is being deprived of for this act of generosity.\r\n\r\n"There needs to be a systematic estimation -- we have none," said Ahsan H Mansur, executive director of the Policy Research Institute of Bangladesh.',
    category_name: "Politics",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "genaral news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 10:50",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667191836767.jpg",
  },
  {
    id: 14,
    headline: "Marc Riboud’s Bangladesh 1971 Mourning and Morning",
    body: "Marc Riboud (1923-2016), one of the first generation of Magnum photographers, was born in Lyon, France. He traveled and worked extensively in the Middle East, Afghanistan, India, China, Japan, Cambodia, North and South Vietnam, the Former Soviet Union, Algeria, and Sub-Saharan Africa throughout the 60s and 70s. His picture of a \"young woman holding a flower,\" taken in front of the Pentagon during a protest against the Vietnam War, became an international symbol of peace.\r\nLorene Durret: I met Marc Riboud about 16 years ago while I was working at Delpire which is a major historical, photography publisher in Paris run by Robert Delpire. He published 'The Americans by Robert Frank and the primary books of Henri Cartier-Bresson, among many others. He was an important figure in the photography world. I worked in his office for about a year and he used to organize Friday lunch with the photographers he was working with, his friends, and his colleagues. That's how I met Marc Riboud!",
    category_name: "Politics",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "opinion",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 10:52",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667191946247.jpg",
  },
  {
    id: 15,
    headline: "Marc Riboud’s Bangladesh 1971 Mourning and Morning",
    body: "Lorene Durret, Director of Les Amis de Marc Riboud, has been working on Marc Riboud's photographic archive for quite a long time. She is currently co-curating an exhibition at Alliance Française de Dhaka, showcasing a selection of Marc Riboud's 50 photographs taken during the Liberation War of Bangladesh. In this conversation with art historian, curator, and co-founder of Duniyadari Archive Amirul Rajiv, Lorene Durret talked about her association with the life and works of Master Photographer Marc Riboud.\r\n\r\nAmirul Rajiv: When did you meet Marc Riboud and begin working with him?\r\n\r\nLorene Durret: I met Marc Riboud about 16 years ago while I was working at Delpire which is a major historical, photography publisher in Paris run by Robert Delpire. He published 'The Americans by Robert Frank and the primary books of Henri Cartier-Bresson, among many others. He was an important figure in the photography world. I worked in his office for about a year and he used to organize Friday lunch with the photographers he was working with, his friends, and his colleagues. That's how I met Marc Riboud!",
    category_name: "Politics",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "opinion",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 10:57",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667192251327.jpg",
  },
  {
    id: 16,
    headline:
      "Superpower rivalry in the knowledge economy: Is the balance of power shifting?",
    body: "Of the world's 114 smartest factories that deploy cutting-edge Fourth Industrial Revolution (4IR) technologies, China owns a whopping 42. In the US, only seven.\r\n\r\nThese factories – lighthouses in the World Economic Forum (WEF) parlance – will lead the world to tomorrow's knowledge economy. A smart factory implements the Internet of Things (IoT), Artificial Intelligence (AI), 3D printing, and advanced robotics to transform the manufacturing process, value chains, and business models. In stiff competition, only a select group of leading companies have successfully deployed such technologies to qualify as lighthouses, symbolizing the superpower race for supremacy in the emerging knowledge economy era. It is an existential question as to who will win this race.\r\nBut what has propelled China to this leading position in the first place? Dr. Marina Zhang of the Swinburne University of Technology, Australia thinks it's the huge innovation machine Beijing launched in the late 1970s that is behind this phenomenal stride. At its heart lies the vision for technological independence. It doesn't just want to make innovative and distinctive products; it wants to do so entirely with its own knowledge, investing heavily to materialize this vision. Between 2000 and 2017, Beijing's spending on research and development (R&D) grew by 17 percent each year. Over the same period, the US dragged far behind with a paltry 4.3 percent growth rate. The trend continues under Beijing's 14th Five-Year Plan (2020-2025) as it intends to increase R&D spending by more than seven percent each year. In 2017, the global R&D spending stood at USD 2.2 trillion, of which 25 and 23 percent came from the US and China, respectively, and the gap is fast closing.\r\n\r\nSo far, Beijing's priority has been more on experimental development that is closely related to manufacturing processes and less on basic and applied research critical to the development of new scientific ideas. In 2018, It spent only five percent of the research budget on basic research compared to the US' 17 percent. For applied research, the corresponding figures were 11 and 20.4 percent, respectively. In contrast, almost 80 percent of China's R&D spending went to experimental development. Acutely aware, Beijing wants to strengthen basic research programs and make groundbreaking innovations. Its researchers are already creating increasing impacts among the global scientific community, as Japan's National Institute of Science and Technology Policy reports. In 2019, about 27.2 percent of the top one percent of the most-cited papers came from Chinese institutions. The US came second with 24.9 percent of such citations. In the total number of publications, Chinese works exceeded those from the US in 2020 (305,927 against 281,487).",
    category_name: "Business",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "opinion",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 11:9",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667192965139.jpg",
  },
  {
    id: 17,
    headline: "How the power crisis is affecting the youth",
    body: "To everyone who believed load-shedding was nostalgia fodder, 2022 has provided a harsh wake-up call. Its unwelcome reintroduction managed to create issues beyond minor discomfort or inconveniences, given how frequent the power outages have become. Much like the rest of the population, young people have been negatively affected in more than one facet of their lives, with their education bearing the brunt of the consequences.\r\n\r\nThe power crisis has aligned with the reopening of educational institutions after the pandemic, which created a myriad of problems. Most educational institutes in the country do not have backup sources of energy, like their own generator or individual IPS units. This means that students are forced to study with the suffocating humidity, which is not only extremely unsuitable for a learning environment, but it can also cause health issues like heat strokes, headaches, and nausea. While regular classes initially continued even without electricity, some institutes needed to halt them after the heat became too unbearable. While some have coped with the crisis by stopping classes altogether, others turned to online classes once again.",
    category_name: "Business",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "arts",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 11:10",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667193034420.jpg",
  },
  {
    id: 18,
    headline: "Audi brings its mountain bicycle to Bangladesh",
    body: "When we hear the name Audi, the first thing that comes to our mind is fast German cars with their famous Quattro All-Wheel Drive system. What most people don't know is that Audi also made bicycles. This bicycle in particular is called Audi Cross Pro RS, produced in 2009. Audi produced a total of only 150 units of this MTB, a very limited number which makes this cycle very exclusive. \r\nAlthough Audi didn't make all the parts themselves, they did source a very impressive combination. The frame itself was Aluminum designed by Audi Sport GmbH, formerly known as Quattro GmbH, the rims were Aluminum as well with a futuristic design. It has the 27-speed Shimano XTR and XT gear derailleurs and gear shifters. The crankset is also from Shimano, it's called XT Hollowtech II, the bottom bracket is integrated with the crank, reducing the overall weight, then again increasing the strength, the brakes as well are from Shimano, they are 2-piston Shimano Deore XT calipers with carbon pads.",
    category_name: "Science & Technology",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "genaral news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 13:19",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667193109650.jpg",
  },
  {
    id: 19,
    headline: "Can an IMF loan rescue Bangladesh's economy?",
    body: "In July 2022, the Bangladesh government approached the International Monetary Fund (IMF) for a loan to address the country's economic challenges. An IMF team is currently in Bangladesh to discuss the details of the loan and prepare for the agreement. We have asked for a USD 4.5 billion loan, which will be provided by IMF's Enhanced Credit Facility (ECF), Enhanced Funding Facility (EFF) program, and the New Initiatives, Resilience and Sustainability Fund (RST).\r\n\r\nThe context under which we are seeking the loan is not uncommon. Our current economic situation is one in which countries usually look to the IMF for the balance of payment support. Our trade deficit is high as import payment is much higher than export income; in FY2021-22, the negative trade balance reached over (-) USD 33 billion. Our current account deficit is also high since remittance flow is negative in the current fiscal year; it amounted to USD 18.7 billion in FY22. This has led to decreasing foreign exchange reserves and depreciation of the Bangladeshi taka. Our forex reserves have come down to USD 35.8 billion from USD 41.8 billion in FY22. As per IMF estimation, the actual reserves are USD 27.4 billion – only enough for about three months' import payments. \r\nOverall, Bangladesh is going through a difficult time; high inflation, food, and fuel crises, and depleting forex reserves have weakened the macroeconomic stability that we have been enjoying for a long time. Global economic shocks caused by the pandemic as well as the ongoing Russia-Ukraine war are bound to affect all economies, irrespective of their development status. However, the scale of the impact depends on the inherent strength of each economy. That strength is achieved through appropriate policies and the implementation of those policies with strong governance.\r\n\r\nUnfortunately, over the years, Bangladesh has failed to strengthen its institutions that are responsible for delivering good economic outcomes. Our financial sector is burdened with a large amount of non-performing loans (NPLs) as loan defaulters are given leeway through various flexible measures. As of June 2022, the amount of defaulted loans stood at Tk 1.25 lakh crore or about nine percent of the total loans disbursed, according to the Bangladesh Bank. Wastage and leakage of resources in projects abound due to a lack of good governance. Domestic resource mobilization efforts are stubbornly slow, and the tax-GDP ratio is only 7.6 percent at present. Added to these problems is the reckless price hike of all commodities, making people's lives miserable.",
    category_name: "Politics",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "hot news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 11:18",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667193516852.png",
  },
  {
    id: 20,
    headline: "‘Rupali Guitar’ award created to honor Ayub Bachchu’s memory",
    body: 'October 18, 2018, was the day Bangladesh lost one of its brightest stars. This was the day Legendary rockstar, Ayub Bachchu passed away.\r\n\r\nIn memory of the star, a special programme was organised yesterday, at a convention centre in Moghbazar. The programme was organised by the Chittagong Musicians Club, Dhaka.\r\nAfter reading the Quran in the afternoon, a discussion—centred around Ayub Bachchu\'s life and career—was held in the evening. Kumar Bishwajit; Partha Barua of Souls; Naquib Khan of Renaissance; Foad Nasser Babu of Feedback; Labu Rahman; Hamin Ahmed, president of Bangladesh Musical Bands Association (BAMBA); Syed Shahid of Durbin, along with other famous artists were a part of this discussion.\r\n\r\nAt the event, Partha Barua announced a special award that had been created in memory of Ayub Bachchu. The current president of Chattogram Musicians Club, Syed Shahid said, "The Rupali Guitar Award will be given every year from now on in memory of Ayub Bachchu. Further details about the award will be revealed in a few days. We believe this award will help to inspire musicians from all over Bangladesh."',
    category_name: "Bangladesh",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "genaral news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 12:24",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667197463704.jpg",
  },
  {
    id: 21,
    headline: "Lula's ups and downs in Brazil defy belief",
    body: "Four years ago, Luiz Inácio Lula da Silva's reputation and political future were in tatters. After an unlikely rise from poverty to union leader to Brazil's presidency, the man universally known as Lula had landed in prison.\r\n\r\nOn Sunday – in yet another twist – Brazilian voters chose him by the narrowest of margins to once again lead the world's fourth-largest democracy. He will also be putting his legacy on the line.\r\n\"They tried to bury me alive, and I am here,\" da Silva said in a speech Sunday night after results that confirmed his third presidential win. \"I am here to govern in a very difficult situation. But I have faith in God that, with our people's help, we will find a way out for this country.\"\r\n\r\nThe life of da Silva has unfolded in such a unique, extraordinary way that it strains credulity.\r\nHis family moved from Brazil's poor northeast region to Sao Paulo state in pursuit of a better life, following his father who had traveled south years before. Upon arriving, however, they found he had settled down with another woman. Da Silva's mother was left alone to raise eight children, of whom little Lula was the youngest.\r\n\r\nPressed for money, he became a metalworker at age 14 in the metropolis' gritty outskirts. It was a physical job that famously cost him his left pinky finger. He became a union leader in an era when Brazil's manufacturing workforce was still vast and translated into political power. He made his first presidential run in 1989, which he lost — along with two subsequent races.\r\n\r\nFinally, in 2002, he claimed victory and became the first worker to assume the nation's top job. And he was reelected four years later, defeating his rival Geraldo Alckmin who, this year, became his running mate.",
    category_name: "Bangladesh",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "genaral news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 12:25",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667197548902.jpeg",
  },
  {
    id: 22,
    headline: "Ban on stone lifting: Goods transport strike in Sylhet",
    body: 'Owners and workers of goods transport enforced a 48-hour strike in Sylhet since this morning (October 31, 2022) seeking permission for manually extracting stones and also demanding a withdrawal ban on stones lifting from quarries. \r\n\r\nThe strike began at 6 am, reports our Sylhet correspondent.\r\nAfter a meeting with the Sylhet district administration on Sunday night (October 30, 2022), the owners and workers of the goods transport confirmed the strike as the meeting was not "fruitful".\r\nEarlier on October 17, Sylhet   Divisional Truck, Pickup Van, and Covered Van Owners-Workers Unity Council announced the strike at a press conference.',
    category_name: "World",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "genaral news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 12:27",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667197645533.jpg",
  },
  {
    id: 23,
    headline: "Sagar-Runi murder: Rab fails to file probe report for 93rd time",
    body: "A Dhaka court today (October 31, 2022) again asked Rapid Action Battalion to submit -- by December 1 -- the probe report of the murder case of journalist couple Sagar Sarowar and Meherun Runi.\r\n\r\nWith this, the deadline for submission of the report has been rescheduled for 93 times.\r\nDhaka Metropolitan Magistrate Md Rashidul Alam passed the order after Rab Additional Superintendent of Police Khondoker Md Shafiqul Alam, also the investigation officer of the case failed to submit the report today, court sources said.\r\n\r\nOn September 26, another Dhaka court asked Rab to submit the probe report by today.\r\nEarlier, two separate courts expressed dissatisfaction over the investigation and their failure to unearth the real clue of the murder and to arrest the real culprits.\r\n\r\nSagar, news editor at private TV channel Maasranga, and his wife Runi, senior reporter at ATN Bangla, were killed in the early hours of February 11, 2012, in their rented flat in the capital's West Razabazar.\r\n\r\nTheir only son Mahir Sarowar Megh, then 5, was home at that time.",
    category_name: "Bangladesh",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "genaral news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 12:28",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667197718342.jpg",
  },
  {
    id: 24,
    headline: "Senior BNP leader Sabihuddin Ahmed no more",
    body: "Senior BNP leader Salahuddin Ahmed, a member of the party's chairperson Khaleda Zia's advisory council, passed away this morning (October 31, 2022).\r\n\r\nHe was 76 years old. He breathed his last around 7:40 am at United Hospital Limited, BNP's media cell member Shairul Kabir Khan told The Daily Star.\r\nHis first namaz-e-janaza will be held at Gulshan Azad Mosque after Isha prayers tomorrow (November 1, 2022).",
    category_name: "World",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "genaral news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 12:30",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667197840627.jpg",
  },
  {
    id: 25,
    headline: "Brazil election: Bolsonaro yet to concede Lula win",
    body: "Brazilian leftist leader Luiz Inacio Lula da Silva narrowly defeated President Jair Bolsonaro in a runoff election, but the far-right incumbent did not concede defeat on Sunday night, raising concerns that he might contest the result.\r\n\r\nThe Supreme Electoral Court (TSE) declared Lula the next president, with 50.9 percent of votes against 49.1 percent for Bolsonaro. The 77-year-old Lula's inauguration is scheduled for January 1.\r\nIt was a stunning comeback for the leftist former president and a punishing blow to Bolsonaro, the first Brazilian incumbent to lose a presidential election.\r\n\"So far, Bolsonaro has not called me to recognize my victory, and I don't know if he will call or if he will recognize my victory,\" Lula told tens of thousands of jubilant supporters celebrating his win on Sao Paulo's Paulista Ave.",
    category_name: "World",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "genaral news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 12:32",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667197924943.jpg",
  },
  {
    id: 26,
    headline: "‘If you take those catches, it's a different thing’",
    body: "Catches win matches, and India's failure to take their chances in the field saw a win slip through their grasp against South Africa in Perth.\r\n\r\nSouth Africa was hobbling along in their chase of just 134 to win against India, limping to just 40/3 at the midway point of the innings after the wickets tumbled early.\r\nSo breaking the partnership between Aiden Markram and David Miller was key to India's chances, and eventually, they did, with Suryakumar Yadav taking a catch in the deep to remove Markram for 52.\r\n\r\nBut by then much of the damage had been done, with the key partnership having added 60 runs in the previous 5.4 overs, putting South Africa in the driving seat in a game that still went down to the final over.\r\nAnd things could have been so different.\r\n\r\nYadav missed a chance to run Markram out early in his innings, and Rohit Sharma failed to hit all three stumps with an even better run-out opportunity later in the partnership with Miller nowhere near making his ground.\r\n\r\nBut the most eye-catching and arguably most disappointing missed opportunity came when Markram, on 35 at the time, skied Ravi Ashwin to Virat Kohli.",
    category_name: "Sports",
    type: "genaral news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 12:33",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667198013115.jpg",
  },
  {
    id: 27,
    headline: "Apple confirmed to introduce USB-C by 2024",
    body: "Apple has confirmed that they will introduce USB-C-supported iPhones by 2024, as per a comment made by Greg Joswiak, Senior Vice President, Worldwide Marketing at Apple Inc. The new direction comes as a response to the European Union mandating USB-C support for future smartphones sold in the EU nations. \r\n\r\nAccording to new legislation by European Union, by 2024, all smartphones sold in the EU must contain a universal USB-C port for wired charging. This ruling extends to other electronic devices such as tablets, headphones, handheld gaming consoles, e-readers, and digital cameras - and of course, the iPhones as well.\r\nThe ruling was made to make common charging more accessible in Europe. As per a press statement made by Alex Agius Saliba, Member of the European Parliament, for a long time, European consumers have faced frustrations regarding multiple chargers being introduced with new devices. According to him, with this legislation now passed, a single charger can be used to charge all portable electronics in the EU nations. \r\n\r\nWhen asked for further comments by The Wall Street Journal, Joswiak refused to confirm if USB-C-supported iPhones would be sold outside the EU as well. Currently, iPhones use Apple's signature Lightning connector for charging and accessory connection purposes.",
    category_name: "Science & Technology",
    type: "features",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 13:31",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667201510731.jpg",
  },
  {
    id: 28,
    headline: "TikTok to soon introduce gaming on the platform: Reports",
    body: 'According to latest the Financial Times report, the popular short video platform TikTok will soon make available a gaming tab on its app that will let users play mobile games. According to the report, these games will have advertisements and users will be able to purchase extra content.\r\n\r\nIn May, TikTok began testing games there for the first time. According to the Financial Times, TikTok\'s moderators in Europe were given the responsibility of testing games before their official launch.\r\nOn November 2, when TikTok is hosting its "first global gaming event" with the slogan "TikTok Made Me Play It," where an announcement is expected regarding the game offers. \r\n\r\n"The future of gaming is here—and it\'s happening on TikTok. Leading publishers are launching games on our platform as culturally relevant entertainment properties, building communities, and inspiring broader entertainment audiences to discover and play their games," reads a description on the event site.\r\n\r\n',
    category_name: "Science & Technology",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "genaral news",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 13:33",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667201632464.jpg",
  },
  {
    id: 29,
    headline: "DFSK EC36: utility, now electric",
    body: 'DFSK, a Chinese company fairly new and rapidly getting popular in the Bangladeshi markets, mostly for producing mid-tier SUVs, are on its way to releasing its first-ever fully electric vehicle. From a general standpoint, it may seem like a reiteration of a recycled SUV design with an added electric powertrain. But some may also call it a new, unorthodox utilitarian minibus. Keep reading to find out more about the new DFSK EC36.\r\n\r\nWhat is it?\r\nThe DFSK EC36 is an 11-seat vehicle designed by the Japanese company folly, coming in two configurations, a minibus or a blind van; there\'s a choice, where the latter eliminates the passenger seats at the back. The EC36 could completely fly under your radar as any standard van on the road because of how "normal" it looks. There is nothing associated with the electric vehicle stigma of being overly angular, having anything doing with sharp edges, or modifying the front end to mute it for better aerodynamics; rather the whole van is "muted" from having the electric vehicle aura, sporting a rather humble design of just any regular van, now with an electric motor. Apart from that, the van comes with 14\'\' wheels across all models.',
    category_name: "Science & Technology",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "living",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 13:35",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667201711244.jpg",
  },
  {
    id: 30,
    headline:
      "Musk fires Parag Agrawal, and others after taking Twitter charge",
    body: 'Elon Musk became Twitter Inc\'s (TWTR.N) owner on Thursday, firing top executives and providing little clarity over how he will achieve the lofty ambitions he has outlined for the influential social media platform.\r\n\r\nThe CEO of electric car maker Tesla Inc (TSLA.O) has said he wants to "defeat" spam bots on Twitter, make the algorithms that determine how content is presented to its users publicly available, and prevent the platform from becoming an echo chamber for hate and division, even as he limits censorship.\r\nYet Musk has not offered details on how he will achieve all this and who will run the company. He has said he plans to cut jobs, leaving Twitter\'s approximately 7,500 employees fretting about their future. He also said on Thursday he did not buy Twitter to make more money but "to try to help humanity, whom I love."',
    category_name: "Science & Technology",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "living",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 13:36",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667201783561.jpg",
  },
  {
    id: 31,
    headline: "Why is workplace safety for women such a big ask?",
    body: "When we talk about Bangladesh's development journey, the role that women have played in propping up the economy is inevitably a part of the conversation. Whether it is as RMG workers, small entrepreneurs or migrant workers, we routinely cite how women's participation in the labour force has not only been beneficial for their economic empowerment, but for the nation as a whole. This is especially true in terms of the RMG industry, where around 60 per cent of the workforce are women.\r\n\r\nBut this proportion has been steadily declining\r\nIn fact, female labour force participation as a whole took a hit during the pandemic, but it is back on the rise again. And, according to data from the International Labour Organization (ILO), it continues to be higher than the South Asian average: in 2021, Bangladesh's female labour force participation rate was 35 per cent, whereas India's was 19 per cent and Sri Lanka's 31 per cent.\r\nHowever, once you get past the microcredit-induced smiles on the glossy papers of different brochures that focus on the transformational abilities of women's labour – and there's no denying that economic empowerment has changed the fates of hundreds of thousands of our women – there are a lot of questions that can be asked about the state of women's work.\r\nHow irregular is it? What is the wage gap? How much of their earnings is under the control of other members of the household? How much longer/harder do they have to work compared to their male counterparts? How do they balance paid employment and the unpaid care work they do at home? How do self-employed women deal with the risks and sudden losses resulting from unprecedented situations such as a pandemic?",
    category_name: "Politics",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "opinion",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 15:4",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667207054779.jpg",
  },
  {
    id: 32,
    headline: "Farmers need better protection against crop losses",
    body: "After every natural calamity, the discussion in Bangladesh tends to veer toward the loss suffered in terms of life. This is perhaps natural, but the death toll is an insufficient indicator of the extent of damage suffered by affected communities. After Cyclone Strang, which killed at least 35 people since lashing Bangladesh midweek, the focus too has been largely on deaths, or the relative lack thereof, if compared to the last few cyclones. But there are bigger concerns for the battered people who, again, must go through a painful process of relief, rehabilitation, and rebuilding to get back on their feet.\r\nThe cyclone has left a trail of destruction that may take months, even years, to recover from. Reports indicate that vast stretches of cropland were devastated. In Khulna, for example, crops, vegetables, and fruits grown on around 18,483 hectares of land have been reportedly damaged due to heavy rains and strong winds. Meanwhile, fish farms on around 23 hectares of land were also damaged. The same thing happened in Tangail. In Bhola, fishing communities were hit particularly hard. In Barguna, Pirojpur, Shariatpur, Noakhali, and other districts, people were similarly affected. Individual accounts from many villages paint a bleak picture as people try to grapple with the post-cyclone reality. Apart from the physical damage to homes and sources of livelihood, there are also concerns about inadequate relief and rehabilitation efforts amidst continued outages in many places, where power lines are yet to be restored.",
    category_name: "World",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "opinion",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 15:5",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667207141879.png",
  },
  {
    id: 33,
    headline: "Don’t let scammers exploit refugees",
    body: "It is clear from recent news reports that the condition of Rohingya refugees in Bangladesh is becoming increasingly vulnerable. On Wednesday, a Rohingya man was picked up from his house in the Balukhali refugee camp and shot dead. The day before, another was killed at the Kutupalong camp. Last week, a young Rohingya man was killed by miscreants, not long after his father was also killed in the Tajnimar Khola 19 camp.\r\n\r\nIn the meantime, the Myanmar military junta has started the process of transferring the ownership of land that originally belonged to Rohingya refugees, often for generations, before they were forced to flee in 2017 – thus adding a new layer of complications to any potential repatriation process.\r\nIn the midst of all this, it is reprehensible that criminal elements have been preying on this vulnerable group of refugees and dangling the carrot of Bangladeshi citizenship in front of them in exchange for exorbitant amounts of money. According to a report in this daily, a syndicate operating from Chattogram city has been charging Tk 1.30 lakh per head to issue fake national identity (NID) cards for Rohingya refugees.\r\n\r\nThis is the third time that such a scam has been discovered in the area. Out of the 10 people who were arrested by Chattogram Metropolitan Police in this connection, we are horrified to find that five are local Election Commission (EC) employees. Police investigations have revealed that these are data entry operators engaged in creating updated voter lists, and they have been abusing their positions to make a quick buck at the expense of national security.",
    category_name: "Bangladesh",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "living",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 15:6",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667207201386.png",
  },
  {
    id: 34,
    headline: "Student politics in private universities: To be or not to be …",
    body: 'On September 2, the student front of a political party announced its intention to form committees in 16 private universities.  It was greeted with apprehension and alarm.  More than 10,000 guardians of students in these universities sent letters expressing their concerns, the administrators overwhelmingly opposed the move, and the Association of Private Universities in Bangladesh rejected the idea outright.\r\n\r\nThey have the legal right to make that choice based on sections 14.1 and 14.2 of the 2010 Act (which amended the Act of 1992 governing private universities) that implicitly provides them that authority. They also felt buoyed by the Education Minister Dr. Dipu Moni\'s wise decision to leave this matter to the Universities. Moreover, the evidence, logic, and ethical foundations of their argument opposing this effort were sincere and compelling. \r\nIt should also be noted that most of the intellectual leaders resisting this proposal are richly credentialed and deeply dedicated educators. Many are personal friends held in much affection and respect.  There is no doubt that their intentions are noble.  But as many pundits, including Marx, have pointed out – the road to hell is paved with good intentions.\r\n\r\nIt is understandable that what passes in the guise of "student politics" in many public universities would naturally evoke anxieties among students, parents, teachers, administrators, trustees, and stakeholders in many private universities who may be justifiably worried about similar pressures and practices being reproduced there.',
    category_name: "Politics",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "opinion",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 15:8",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667207287218.jpg",
  },
  {
    id: 35,
    headline: "Benefits of using olive oil for a healthy skin",
    body: "Olive oil, made by pressing olives and extracting oil from them, is very beneficial for healthy skin. Rich in antioxidants and vitamins that improve the moisturization process of the skin, while also enhancing anti-aging effects, olive oil presents an effective option for an ideal skincare routine. Let's take a look at some of the benefits of olive oil for your skin.\r\n\r\nMoisturising of the skin\r\nOne of the biggest benefits of olive oil is it moisturizes by reducing the amount of water your skin loses. Olive oil is full of vitamin A and E, but also other vitamins like D and K which helps shield even the most delicate of skins. Whether using it as a moisturizer or by mixing it with your night cream, olive oil adapts to your skin effortlessly.\r\nFixing damaged skin tissues\r\nWhether it's the cracked skin on elbows or knees or superficial wounds, using olive oil offers an ideal solution. Furthermore, olive oil also regulates certain bacteria's appearance on the face, making it effective against acne. The vitamin D in olive oil also helps against skin conditions like rosacea and psoriasis by calming down the inflammation.\r\n\r\nRevitalize your face\r\nOlive oil is known to stimulate the production of collagen in your skin and its high concentration of oleic acid helps in regenerating your skin cells, giving your skin the elasticity and natural shine that it needs.",
    category_name: "Health",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "living",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 15:10",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667207442796.jpg",
  },
  {
    id: 36,
    headline:
      "Traveling through Sicily: How to prolong summer under the Sicilian sun",
    body: "As a Bangladeshi living in Berlin, I am perpetually cold. The city has one month of proper summer when the native Berliners or northern Europeans all melt under the heat and I flourish like a Sunflower in full bloom. So, when I realized that come September, the city would somehow drop 13° and become unbearably cold for 'autumn,' I thought what better way to prolong summer than to escape to Sicily for a long weekend with a good friend (also Bengali). And so, we did, booking a trip three months in advance, knowing full well we would love our past selves for this — boy was we right because Sicily is an absolute delight. \r\nFrom the moment we got to Sicily, we felt a sense of familiarity with the island, it is as if we had been there in another lifetime, and this was no different from our connection with Tanja, who felt like a soul we had certainly encountered in another lifetime. We drove for one-and-a-half hours from the airport to Casalovecchio, a beautiful ride through the rolling hills to the tiny village on top of a hill. \r\n\r\nNow picture this; a tiny Italian village, carved in stone paths, with cute little homes stacked next to each other, with a view of the beautiful green hills that it sits on top of. And on the horizon, you can see the sea, blue, sparkling, and enticing. ",
    category_name: "Travel",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "living",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 15:11",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667207511845.jpg",
  },
  {
    id: 37,
    headline: "Why go nuts: All the benefits you can reap",
    body: "Consuming nuts as part of a healthy diet may be beneficial to health. Nuts are high in unsaturated fatty acids and other nutrients. They are also great as a snack because they are cheap, easy to store, and portable. One disadvantage of nuts is that some are high in calories, so portion control is essential. However, choosing nuts over a less healthy snack may help you stick to a heart-healthy diet.\r\n\r\nNuts are widely praised for their delicious flavor and ease of preparation, but the flavor is not the only reason they are so popular. Scientists have long lauded the health benefits of including nuts in your daily diet.\r\nThere are numerous types of nuts. Raw mixed nuts typically include almonds, pistachios, cashews, walnuts, hazelnuts, etc. They are easy to find at almost any grocery store, and they are loaded with nutrients.\r\n\r\nHealth benefits\r\nNuts are a nutrient-dense food that contains the majority of the vitamins and minerals the body requires. They are a major source of alpha-lipoic acid (ALA), and omega-3 fatty acids that have a wide range of health benefits, from reducing rheumatoid arthritis to protecting against Alzheimer's and dementia.",
    category_name: "Foods",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "living",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 15:12",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667207571818.jpg",
  },
  {
    id: 38,
    headline: "Huawei, BGMEA to promote the use of green energy in factories",
    body: "The ICT infrastructure provider Huawei today signed a memorandum of understanding (MoU) with the Bangladesh Garment Manufacturers and Exporters Association (BGMEA) to address the current energy crisis and move towards building a greener Bangladesh.\r\n\r\nFaruque Hassan, president of the BGMEA, and Pan Junfeng, CEO of Huawei Technologies (Bangladesh) Limited, signed the MoU at the BGMEA Complex in Dhaka.\r\nUnder the agreement, Huawei and BGMEA will work together to help garment factories become 'green factories' by shifting to green sources of energy.\r\n\r\nHuawei will be setting up solar power plants in the BGMEA enlisted factories, according to a statement from the BGMEA.",
    category_name: "Science & Technology",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "arts",
    editor_name: "Iqbal Hossen",
    date: "31 October, 2022 15:14",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667207669057.jpg",
  },
  {
    id: 39,
    headline: "Dry weather likely over the country: BMD",
    body: "The weather may remain dry with a temporary partly cloudy sky over the country in the next 24 hours, the met office has said.\r\n\r\nThe day and night temperatures may remain nearly unchanged over the country, said the recent weather bulletin from Bangladesh Meteorological Department (BMD).\r\nHowever, there will be a little change in weather in the next 72 hours, it said.\r\n\r\nThere was no trace of rain across the country in 24 hours till 6 am today (October 28, 2022).\r\nThe lowest temperature was recorded in Srimangal at 18 degrees Celsius, while the highest temperature was 33 degrees in Khulna.",
    category_name: "World",
    category_id: 1,
    sub_category_name: "",
    sub_category_id: null,
    user_id: 1,
    updated_at: null,
    type: "arts",
    editor_name: "Iqbal Hossen",
    date: "3 November, 2022 13:59",
    created_at: "2022-11-22T18:00:00.000Z",
    image: "image-1667207741273.jpg",
  },
];
